version: '3'
services:
  backend:
    image: my-app:1.0
    container_name: backend
    ports:
      - '5000:5000'
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    ports:
      - '27017:27017'

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
